name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install required packages
        run: >-
          DEBIAN_FRONTEND=noninteractive
          sudo apt-get install
          bash
          busybox
          dash
          ksh
          shellcheck

      - uses: actions/checkout@v2

      - name: Run tests
        run: make test
